[HMI]
sampling_rate_ms = 50
address = 1

[RPI]
evoflow_reset_gpio_pin = 17
evoflow_status_gpio_pin = 27


[Evoflow]
port_windows = COM6
; port_macos = /dev/cu.usbserial-DK0GU7KF
port_macos = /dev/cu.usbserial-AB0P7C53
port_linux = /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DK0GU7KF-if00-port0
serial_timeout = 0.02
baudrate = 921600
address = 100
auto_reset_after_seconds = 30

[ODController]
V0 = 30.0
A0 = 0.63
mu0 = 0.000256
kp = -0.00864
ki = -0.0000108
q_max = 0.01111111111111112
q_lagoon_max = 0.00778
Ts = 0.5
A_setpoint = 0.65
f = 2.5
Tb = 50

; V0 (ml) Volume of the bioreactor
; A0 (OD) Initial optical density
; mu0 (1/s) bacterial growth
; kp (ml/s)
; ki (ml/s^2)
; q_max (ml/s) Maximum flow rate of the pump
; q_lagoon_max (ml/s) Maximum flow rate of the lagoon pump to keep the bioreator volume constant
; Ts (s) Sampling time for the control loop
; A_setpoint (OD) Setpoint for the optical density
; f (%) Fraction of the q_max that allows the integral to contribute to the control action. (anti_windup_limit = (f * q_max)/(V0 * ki)) -> Systematic tuning
; Tb (s) Time constant for back-calculation anti-windup. (back_calculation_gain = Ts/(Tb * V0 * ki)) -> Systematic tuning

[SampleExtraction]
port_windows = COM7
port_macos = /dev/cu.usbserial-FTDI_SAMPLE_EXTRACTOR
port_linux = /dev/ttyUSB1
serial_timeout = 0.5
baudrate = 921600
address = 101

[defaultValues]
pump1_flow = 0.0
pump2_flow = 0.0
pump3_flow = 0.0
pump4_flow = 0.0
magneticStirrer_bioreactor_rpm = 3000
magneticStirrer_lagoon_rpm = 3000
tempCtrl_bioreactor_sp = 37
tempCtrl_lagoon_sp = 37

[defaultComponentStatus]
pump1_status = False
pump2_status = False
pump3_status = False
pump4_status = False
magneticStirrer_bioreactor_status = False
magneticStirrer_lagoon_status = False
tempCtrl_bioreactor_status = False
tempCtrl_lagoon_status = False
od_bioreactor_status = False
od_lagoon_status = False
od_lagoon_enabled = False
phtCount_status = False
sug2lagValve_status = False
bio2lagValve_status = False

[flowRateConversionFactors]
; Fitted polynomial coefficients for Pump 1: [-1.90969190e-04  1.48618164e+00  8.05291619e+00]
; R-squared value: 0.9993
; Fitted polynomial coefficients for Pump 2: [-3.81551185e-04  1.65451022e+00  4.88663718e+00]
; R-squared value: 0.9998
; Fitted polynomial coefficients for Pump 3: [-3.56038585e-04  1.49877596e+00  7.38960221e+00]
; R-squared value: 0.9996
; Fitted polynomial coefficients for Pump 4: [-4.61969304e-04  1.40346600e+00  7.85121406e+00]
; R-squared value: 0.9997
pump_1 = -1.90969190e-04,1.48618164e+00,8.05291619e+00
pump_2 = -3.81551185e-04,1.65451022e+00,4.88663718e+00
pump_3 = -3.56038585e-04,1.49877596e+00,7.38960221e+00
pump_4 = -4.61969304e-04,1.40346600e+00,7.85121406e+00

[plotConfiguration]
timespan_minutes = 5
sampling_time_seconds = 5
y_axis_flowRate_min = 0
y_axis_flowRate_max = 5
y_axis_phtCount_min = 0
y_axis_phtCount_max = 40
y_axis_temp_min = 20
y_axis_temp_max = 40
y_axis_od_min = 0
y_axis_od_max = 1.5
scrollbar_max_loading_value = 2500
max_data_points_to_load = 7200

[dataLogging]
max_rows_per_db = 10000
